networks:
  event-manager:

services:
  gateway-service:
    container_name: gateway-service
    build: 
      context: ../em-gateway-service
      dockerfile: Dockerfile
    image: gateway-service
    ports:
      - "3000:3000"
    volumes:
      - ../em-gateway-service/:/app
      - /app/node_modules
    networks:
      event-manager:
        aliases: 
          - gateway-service
    depends_on:
      - postgres
      # - redis

  events-service:
    container_name: events-service
    build: 
      context: ../em-events-service
      dockerfile: Dockerfile
    image: events-service
    ports:
      - "3001:3000"
    volumes:
      - ../em-events-service/:/app
      - /app/node_modules
    networks:
      event-manager:
        aliases: 
          - events-service
    depends_on:
      - postgres
      # - redis
      - gateway-service

  fans-service:
    container_name: fans-service
    build: 
      context: ../em-fans-service
      dockerfile: Dockerfile
    image: fans-service
    ports:
      - "3002:3000"
    volumes:
      - ../em-fans-service/:/app
      - /app/node_modules
    networks:
      event-manager:
        aliases: 
          - fans-service
    depends_on:
      - postgres
      # - redis
      - gateway-service

  postgres:
    container_name: event-manager-postgres
    image: postgres
    restart: always
    ports:
      - '5678:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=event-manager
    networks:
      event-manager:
        aliases: 
          - postgres


  # redis:
  #   container_name: event-manager-redis
  #   image: redis:latest
  #   ports:
  #     - '6379:6379'
  #   restart: always
